-- Generated by AutoForge. Do not edit manually.
-- Module: signal
-- Placement: sharded

CREATE TABLE signal_subscriptions (
    subscription_id UUID PRIMARY KEY,
    user_id UUID NOT NULL,
    stock_code TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX ix_signal_subscriptions_user_id ON signal_subscriptions (user_id);

CREATE INDEX ix_signal_subscriptions_stock_code ON signal_subscriptions (stock_code);
