-- Generated by AutoForge. Do not edit manually.
-- Module: brokerage_account
-- Placement: sharded

CREATE TABLE brokerage_account_connections (
    connection_id UUID PRIMARY KEY,
    user_id UUID NOT NULL,
    provider TEXT NOT NULL,
    environment TEXT NOT NULL,
    display_name TEXT NOT NULL,
    account_mask TEXT NOT NULL,
    credential_ref TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX ix_brokerage_account_connections_user_id ON brokerage_account_connections (user_id);
