-- Generated by AutoForge. Do not edit manually.
-- Module: account
-- Placement: sharded

CREATE TABLE user_profiles (
    user_id UUID PRIMARY KEY,
    investment_experience TEXT NOT NULL,
    risk_tolerance TEXT NOT NULL,
    investment_goal TEXT NOT NULL,
    monthly_budget DOUBLE PRECISION NOT NULL,
    profile_completed BOOLEAN NOT NULL DEFAULT FALSE
);
