-- Generated by AutoForge. Do not edit manually.
-- Module: notification
-- Placement: sharded

CREATE TABLE in_app_notifications (
    notification_id UUID PRIMARY KEY,
    delivery_intent_id UUID NOT NULL,
    user_id UUID NOT NULL,
    signal_id UUID NOT NULL,
    stock_code TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    read_at TIMESTAMPTZ
);

CREATE INDEX ix_in_app_notifications_delivery_intent_id ON in_app_notifications (delivery_intent_id);

CREATE INDEX ix_in_app_notifications_user_id ON in_app_notifications (user_id);

CREATE INDEX ix_in_app_notifications_signal_id ON in_app_notifications (signal_id);

CREATE INDEX ix_in_app_notifications_stock_code ON in_app_notifications (stock_code);

CREATE INDEX ix_in_app_notifications_created_at ON in_app_notifications (created_at);

CREATE INDEX ix_in_app_notifications_read_at ON in_app_notifications (read_at);
