-- Generated by AutoForge. Do not edit manually.
-- Module: portfolio
-- Placement: sharded

CREATE TABLE portfolio_snapshots (
    snapshot_id UUID PRIMARY KEY,
    connection_id UUID NOT NULL,
    user_id UUID NOT NULL,
    captured_at TIMESTAMPTZ NOT NULL,
    position_count BIGINT NOT NULL
);

CREATE INDEX ix_portfolio_snapshots_connection_id ON portfolio_snapshots (connection_id);

CREATE INDEX ix_portfolio_snapshots_user_id ON portfolio_snapshots (user_id);

CREATE TABLE portfolio_position_snapshots (
    position_id UUID PRIMARY KEY,
    snapshot_id UUID NOT NULL,
    user_id UUID NOT NULL,
    stock_code TEXT NOT NULL,
    product_name TEXT NOT NULL,
    holding_quantity TEXT NOT NULL,
    orderable_quantity TEXT NOT NULL,
    current_price TEXT NOT NULL
);

CREATE INDEX ix_portfolio_position_snapshots_snapshot_id ON portfolio_position_snapshots (snapshot_id);

CREATE INDEX ix_portfolio_position_snapshots_user_id ON portfolio_position_snapshots (user_id);

CREATE INDEX ix_portfolio_position_snapshots_stock_code ON portfolio_position_snapshots (stock_code);
