port 26379
dir /tmp
sentinel monitor kis-session 172.28.0.10 6379 2
sentinel down-after-milliseconds kis-session 2000
sentinel failover-timeout kis-session 10000
sentinel parallel-syncs kis-session 1
