-- Generated by AutoForge. Do not edit manually.
-- Module: market_data
-- Placement: global

CREATE TABLE market_price_snapshots (
    snapshot_id UUID PRIMARY KEY,
    stock_code TEXT NOT NULL,
    current_price TEXT NOT NULL,
    observed_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX ix_market_price_snapshots_stock_code ON market_price_snapshots (stock_code);

CREATE INDEX ix_market_price_snapshots_observed_at ON market_price_snapshots (observed_at);
