-- Generated by AutoForge. Do not edit manually.
-- Module: identity
-- Placement: global

CREATE TABLE login_accounts (
    user_id UUID PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL
);
