-- Generated by AutoForge. Do not edit manually.
-- Module: identity
-- Placement: global

CREATE TABLE login_accounts (
    user_id UUID PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    access_level TEXT NOT NULL DEFAULT 'user',
    shard_id TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE access_level_audits (
    audit_id UUID PRIMARY KEY,
    subject_user_id UUID NOT NULL,
    actor TEXT NOT NULL,
    previous_access_level TEXT NOT NULL,
    new_access_level TEXT NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL
);
