-- Generated by AutoForge. Do not edit manually.
-- Module: news
-- Placement: global

CREATE TABLE news_articles (
    source_key TEXT PRIMARY KEY,
    source_url TEXT NOT NULL,
    provider TEXT NOT NULL,
    title TEXT NOT NULL,
    content TEXT,
    symbol TEXT NOT NULL,
    published_at TIMESTAMPTZ,
    publisher TEXT,
    collected_at TIMESTAMPTZ NOT NULL
);
