-- Generated by AutoForge. Do not edit manually.
-- Module: market_history
-- Placement: global

CREATE TABLE domestic_daily_candles (
    candle_id UUID PRIMARY KEY,
    stock_code TEXT NOT NULL,
    trading_date TEXT NOT NULL,
    open_price TEXT NOT NULL,
    high_price TEXT NOT NULL,
    low_price TEXT NOT NULL,
    close_price TEXT NOT NULL,
    volume BIGINT NOT NULL
);

CREATE INDEX ix_domestic_daily_candles_stock_code ON domestic_daily_candles (stock_code);

CREATE INDEX ix_domestic_daily_candles_trading_date ON domestic_daily_candles (trading_date);
