-- Generated by AutoForge. Do not edit manually.
-- Module: signal
-- Placement: global

CREATE TABLE signal_delivery_intents (
    intent_id UUID PRIMARY KEY,
    signal_id UUID NOT NULL,
    subscription_id UUID NOT NULL,
    user_id UUID NOT NULL,
    shard_id TEXT NOT NULL,
    stock_code TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending'
);

CREATE INDEX ix_signal_delivery_intents_signal_id ON signal_delivery_intents (signal_id);

CREATE INDEX ix_signal_delivery_intents_subscription_id ON signal_delivery_intents (subscription_id);

CREATE INDEX ix_signal_delivery_intents_user_id ON signal_delivery_intents (user_id);

CREATE INDEX ix_signal_delivery_intents_stock_code ON signal_delivery_intents (stock_code);

CREATE INDEX ix_signal_delivery_intents_expires_at ON signal_delivery_intents (expires_at);

ALTER TABLE signal_events ADD COLUMN expires_at TIMESTAMPTZ;

CREATE INDEX ix_signal_events_expires_at ON signal_events (expires_at);
