from typing import Protocol


class KeyValueStoreClient(Protocol):
    async def health_check(self) -> None: ...

    async def get(self, key: str) -> str | None: ...

    async def set(
        self, key: str, value: str, *, ttl_seconds: int | None = None
    ) -> None: ...

    async def delete(self, key: str) -> bool: ...

    async def aclose(self) -> None: ...
